name: SportsClaw Site Build

on:
  push:
    tags:
      - "v*.*.*"

env:
  APP_NAME: sportsclaw-site
  AKS_CLUSTER_NAME: mks-community-cluster
  AKS_RESOURCE_GROUP: mks-community-group
  DEPLOYMENT_NAME: sportsclaw-site-deployment
  CONTAINER_NAME: sportsclaw-site
  NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name as release version
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Prepare site assets
        run: cp scripts/install.sh site/install.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./site
          file: ./site/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.RELEASE_NAME }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.CONTAINER_NAME }}=${{ secrets.REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.RELEASE_NAME }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
